// Mocks generated by Mockito 5.4.6 from annotations
// in how_many_mobile_meeple/test/platform/web/url_fragment_extractor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUri_0 extends _i1.SmartFake implements Uri {
  _FakeUri_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Uri].
///
/// See the documentation for Mockito's code generation for more information.
class MockUri extends _i1.Mock implements Uri {
  MockUri() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get scheme => (super.noSuchMethod(
        Invocation.getter(#scheme),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#scheme),
        ),
      ) as String);

  @override
  String get authority => (super.noSuchMethod(
        Invocation.getter(#authority),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#authority),
        ),
      ) as String);

  @override
  String get userInfo => (super.noSuchMethod(
        Invocation.getter(#userInfo),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#userInfo),
        ),
      ) as String);

  @override
  String get host => (super.noSuchMethod(
        Invocation.getter(#host),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#host),
        ),
      ) as String);

  @override
  int get port => (super.noSuchMethod(
        Invocation.getter(#port),
        returnValue: 0,
      ) as int);

  @override
  String get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#path),
        ),
      ) as String);

  @override
  String get query => (super.noSuchMethod(
        Invocation.getter(#query),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#query),
        ),
      ) as String);

  @override
  String get fragment => (super.noSuchMethod(
        Invocation.getter(#fragment),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#fragment),
        ),
      ) as String);

  @override
  List<String> get pathSegments => (super.noSuchMethod(
        Invocation.getter(#pathSegments),
        returnValue: <String>[],
      ) as List<String>);

  @override
  Map<String, String> get queryParameters => (super.noSuchMethod(
        Invocation.getter(#queryParameters),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  Map<String, List<String>> get queryParametersAll => (super.noSuchMethod(
        Invocation.getter(#queryParametersAll),
        returnValue: <String, List<String>>{},
      ) as Map<String, List<String>>);

  @override
  bool get isAbsolute => (super.noSuchMethod(
        Invocation.getter(#isAbsolute),
        returnValue: false,
      ) as bool);

  @override
  bool get hasScheme => (super.noSuchMethod(
        Invocation.getter(#hasScheme),
        returnValue: false,
      ) as bool);

  @override
  bool get hasAuthority => (super.noSuchMethod(
        Invocation.getter(#hasAuthority),
        returnValue: false,
      ) as bool);

  @override
  bool get hasPort => (super.noSuchMethod(
        Invocation.getter(#hasPort),
        returnValue: false,
      ) as bool);

  @override
  bool get hasQuery => (super.noSuchMethod(
        Invocation.getter(#hasQuery),
        returnValue: false,
      ) as bool);

  @override
  bool get hasFragment => (super.noSuchMethod(
        Invocation.getter(#hasFragment),
        returnValue: false,
      ) as bool);

  @override
  bool get hasEmptyPath => (super.noSuchMethod(
        Invocation.getter(#hasEmptyPath),
        returnValue: false,
      ) as bool);

  @override
  bool get hasAbsolutePath => (super.noSuchMethod(
        Invocation.getter(#hasAbsolutePath),
        returnValue: false,
      ) as bool);

  @override
  String get origin => (super.noSuchMethod(
        Invocation.getter(#origin),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.getter(#origin),
        ),
      ) as String);

  @override
  bool isScheme(String? scheme) => (super.noSuchMethod(
        Invocation.method(
          #isScheme,
          [scheme],
        ),
        returnValue: false,
      ) as bool);

  @override
  String toFilePath({bool? windows}) => (super.noSuchMethod(
        Invocation.method(
          #toFilePath,
          [],
          {#windows: windows},
        ),
        returnValue: _i2.dummyValue<String>(
          this,
          Invocation.method(
            #toFilePath,
            [],
            {#windows: windows},
          ),
        ),
      ) as String);

  @override
  Uri replace({
    String? scheme,
    String? userInfo,
    String? host,
    int? port,
    String? path,
    Iterable<String>? pathSegments,
    String? query,
    Map<String, dynamic>? queryParameters,
    String? fragment,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #replace,
          [],
          {
            #scheme: scheme,
            #userInfo: userInfo,
            #host: host,
            #port: port,
            #path: path,
            #pathSegments: pathSegments,
            #query: query,
            #queryParameters: queryParameters,
            #fragment: fragment,
          },
        ),
        returnValue: _FakeUri_0(
          this,
          Invocation.method(
            #replace,
            [],
            {
              #scheme: scheme,
              #userInfo: userInfo,
              #host: host,
              #port: port,
              #path: path,
              #pathSegments: pathSegments,
              #query: query,
              #queryParameters: queryParameters,
              #fragment: fragment,
            },
          ),
        ),
      ) as Uri);

  @override
  Uri removeFragment() => (super.noSuchMethod(
        Invocation.method(
          #removeFragment,
          [],
        ),
        returnValue: _FakeUri_0(
          this,
          Invocation.method(
            #removeFragment,
            [],
          ),
        ),
      ) as Uri);

  @override
  Uri resolve(String? reference) => (super.noSuchMethod(
        Invocation.method(
          #resolve,
          [reference],
        ),
        returnValue: _FakeUri_0(
          this,
          Invocation.method(
            #resolve,
            [reference],
          ),
        ),
      ) as Uri);

  @override
  Uri resolveUri(Uri? reference) => (super.noSuchMethod(
        Invocation.method(
          #resolveUri,
          [reference],
        ),
        returnValue: _FakeUri_0(
          this,
          Invocation.method(
            #resolveUri,
            [reference],
          ),
        ),
      ) as Uri);

  @override
  Uri normalizePath() => (super.noSuchMethod(
        Invocation.method(
          #normalizePath,
          [],
        ),
        returnValue: _FakeUri_0(
          this,
          Invocation.method(
            #normalizePath,
            [],
          ),
        ),
      ) as Uri);
}
