// Mocks generated by Mockito 5.4.6 from annotations
// in how_many_mobile_meeple/test/platform/web/url_fragment_encoder_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:how_many_mobile_meeple/model/item.dart' as _i5;
import 'package:how_many_mobile_meeple/model/items.dart' as _i4;
import 'package:how_many_mobile_meeple/model/setting.dart' as _i2;
import 'package:how_many_mobile_meeple/model/settings.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSetting_0 extends _i1.SmartFake implements _i2.Setting {
  _FakeSetting_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSettings_1 extends _i1.SmartFake implements _i3.Settings {
  _FakeSettings_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [Items].
///
/// See the documentation for Mockito's code generation for more information.
class MockItems extends _i1.Mock implements _i4.Items {
  MockItems() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Item> get itemList => (super.noSuchMethod(
        Invocation.getter(#itemList),
        returnValue: <_i5.Item>[],
      ) as List<_i5.Item>);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
      ) as bool);

  @override
  set itemList(List<_i5.Item>? value) => super.noSuchMethod(
        Invocation.setter(
          #itemList,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String toUrlItems() => (super.noSuchMethod(
        Invocation.method(
          #toUrlItems,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #toUrlItems,
            [],
          ),
        ),
      ) as String);
}

/// A class which mocks [Settings].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettings extends _i1.Mock implements _i3.Settings {
  MockSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i2.Setting> get allSettings => (super.noSuchMethod(
        Invocation.getter(#allSettings),
        returnValue: <String, _i2.Setting>{},
      ) as Map<String, _i2.Setting>);

  @override
  Map<String, _i2.Setting> get changedSettings => (super.noSuchMethod(
        Invocation.getter(#changedSettings),
        returnValue: <String, _i2.Setting>{},
      ) as Map<String, _i2.Setting>);

  @override
  Map<String, _i2.Setting> get enabledSettings => (super.noSuchMethod(
        Invocation.getter(#enabledSettings),
        returnValue: <String, _i2.Setting>{},
      ) as Map<String, _i2.Setting>);

  @override
  _i2.Setting setting(String? name) => (super.noSuchMethod(
        Invocation.method(
          #setting,
          [name],
        ),
        returnValue: _FakeSetting_0(
          this,
          Invocation.method(
            #setting,
            [name],
          ),
        ),
      ) as _i2.Setting);

  @override
  void updateSetting(_i2.Setting? setting) => super.noSuchMethod(
        Invocation.method(
          #updateSetting,
          [setting],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateAllSettings(_i3.Settings? settings) => super.noSuchMethod(
        Invocation.method(
          #updateAllSettings,
          [settings],
        ),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, String> toQueryParameters() => (super.noSuchMethod(
        Invocation.method(
          #toQueryParameters,
          [],
        ),
        returnValue: <String, String>{},
      ) as Map<String, String>);

  @override
  _i3.Settings clone() => (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
        ),
        returnValue: _FakeSettings_1(
          this,
          Invocation.method(
            #clone,
            [],
          ),
        ),
      ) as _i3.Settings);
}
