abstract class Mechanics {
  static List<String> popularMechanics = <String>[
    "Hand Management",
    "Variable Player Powers",
    "Set Collection",
    "Dice Rolling",
    "Card Drafting",
    "Team-Based Game",
    "Cooperative Game",
    "Tile Placement",
    "Simultaneous Action Selection",
    "Grid Movement",
  ];

  static List<String> bggMechanics = <String>[
    "Acquiring and Losing Workers",
    "Acting",
    "Action Points",
    "Action Queue",
    "Area Majority / Influence",
    "Area Movement",
    "Auction/Bidding",
    "Betting and Bluffing",
    "Campaign / Battle Card Driven",
    "Card Drafting",
    "Competitive Games",
    "Cooperative Game",
    "Deck, Bag, and Pool Building",
    "Dice Rolling",
    "Drafting",
    "Enclosure",
    "Fixed Turn Order",
    "Grid Movement",
    "Hand Management",
    "Increase Value of Unchosen Resources",
    "Line Drawing",
    "Memory",
    "Modular Board",
    "Network and Route Building",
    "Paper-and-Pencil",
    "Pattern Building",
    "Pattern Recognition",
    "Pick-up and Deliver",
    "Player Elimination",
    "Point to Point Movement",
    "Push Your Luck",
    "Role Playing",
    "Roll / Spin and Move",
    "Secret Unit Deployment",
    "Set Collection",
    "Simulation",
    "Simultaneous Action Selection",
    "Solo / Solitaire Game",
    "Storytelling",
    "Take That",
    "Team-Based Game",
    "Tile Placement",
    "Time Track",
    "Trading",
    "Traitor Game",
    "Variable Phase Order",
    "Variable Player Powers",
    "Victory Points from Player Action",
    "Voting",
    "Worker Placement",
  ];
}
