abstract class Mechanics {

  static List<String> popularMechanics = <String>[
    "Area Control / Area Influence",
    "Card Drafting",
    "Cooperative Play",
    "Dice Rolling",
    "Grid Movement",
    "Hand Management",
    "Modular Board",
    "Set Collection",
    "Tile Placement",
    "Variable Player Powers",
    "Worker Placement",
  ];

  static List<String> bggMechanics = <String>[
    "Acting",
    "Action / Movement Programming",
    "Action Point Allowance System",
    "Area Control / Area Influence",
    "Area Enclosure",
    "Area Movement",
    "Area-Impulse",
    "Auction/Bidding",
    "Betting/Wagering",
    "Campaign / Battle Card Driven",
    "Card Drafting",
    "Chit-Pull System",
    "Commodity Speculation",
    "Cooperative Play",
    "Crayon Rail System",
    "Deck / Pool Building",
    "Dice Rolling",
    "Grid Movement",
    "Hand Management",
    "Hex-and-Counter",
    "Hidden Traitor",
    "Line Drawing",
    "Memory",
    "Modular Board",
    "Paper-and-Pencil",
    "Partnerships",
    "Pattern Building",
    "Pattern Recognition",
    "Pick-up and Deliver",
    "Player Elimination",
    "Point to Point Movement",
    "Press Your Luck",
    "Rock-Paper-Scissors",
    "Role Playing",
    "Roll / Spin and Move",
    "Rondel",
    "Route/Network Building",
    "Secret Unit Deployment",
    "Set Collection",
    "Simulation",
    "Simultaneous Action Selection",
    "Singing",
    "Stock Holding",
    "Storytelling",
    "Take That",
    "Tile Placement",
    "Time Track",
    "Trading",
    "Trick-taking",
    "Variable Phase Order",
    "Variable Player Powers",
    "Voting",
    "Worker Placement"
  ];
}
